return marketInfo from quote
HedvigInsurance/underwriter pull request #138
Opened 2020-10-08 08:58 UTC by meletios

Returns the market info based on the quote type. 

This will be used in payment-service as a fail-safe if payment-service cannot determine the market from the contacts

2020-10-08 11:05 UTC, FredrikAreschoug approved these changes
Just a question is it not better to go on picked local from member service? When it comes to context this is really out of place. And also cant this be branched of `feature/enable-danish-signing-through-uw` hence I've been trying to merge that branch for 2 days

2020-10-08 11:05 UTC, FredrikAreschoug commented on src/main/kotlin/com/hedvig/underwriter/service/QuoteService.kt
> +    fun getMarketInfoFromLatestQuote(memberId: String): MarketInfo
I really don't like using latest quote like this but to be fair it will probably be sufficient.

2020-10-08 11:15 UTC, vonElfvin reviewed
I agree that we should consider the pickedLocale. But IMO the hierarchy is like this

Contract > Quote > Picked Locale

Where the previous is more accurate market than the next.

2020-10-08 11:20 UTC, vonElfvin commented on src/main/kotlin/com/hedvig/underwriter/model/MarketInfo.kt
> +class MarketInfo(
```suggestion
class QuoteMarketInfo(
```

2020-10-09 11:09 UTC, FredrikAreschoug requested changes
Just came up with a solution to my comment lets not use the latest quote to decide the market information but use all member's quotes. If they are all, let's say, Norwegian then return the market information otherwise blow up or something because the member is then in a super weird state. I know it can feel like an overkill but I really want to remove the concept of the latest quote

2020-10-21 15:11 UTC, FredrikAreschoug approved these changes
:tada:

2020-10-22 15:05 UTC, FredrikAreschoug approved these changes

2020-10-22 19:38 UTC, merged